services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 8000
      DEBUG: "False"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/results:/app/results
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - "80:80"
